export const GET_COMMENT_BY_COURSE_ID_REQUEST = "GET_COMMENT_BY_COURSE_ID_REQUEST";
export const GET_COMMENT_BY_COURSE_ID_SUCCESS = "GET_COMMENT_BY_COURSE_ID_SUCCESS";
export const GET_COMMENT_BY_COURSE_ID_FAIL = "GET_COMMENT_BY_COURSE_ID_FAIL";
export const GET_COMMENT_BY_COURSE_ID_RESET = "GET_COMMENT_BY_COURSE_ID_RESET";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";