export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";
export const COURSE_LIST_RESET = "COURSE_LIST_RESET";

export const COURSE_LIST_PAGING_REQUEST = "COURSE_LIST_PAGING_REQUEST";
export const COURSE_LIST_PAGING_SUCCESS = "COURSE_LIST_PAGING_SUCCESS";
export const COURSE_LIST_PAGING_FAIL = "COURSE_LIST_PAGING_FAIL";
export const COURSE_LIST_PAGING_RESET = "COURSE_LIST_PAGING_RESET";

export const COURSE_RANDOM_REQUEST = "COURSE_RANDOM_REQUEST";
export const COURSE_RANDOM_SUCCESS = "COURSE_RANDOM_SUCCESS";
export const COURSE_RANDOM_FAIL = "COURSE_RANDOM_FAIL";
export const COURSE_RANDOM_RESET = "COURSE_RANDOM_RESET";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";
export const COURSE_DETAILS_RESET = "COURSE_DETAILS_RESET";

export const COURSE_TOP_RATED_REQUEST = "COURSE_TOP_RATED_REQUEST";
export const COURSE_TOP_RATED_SUCCESS = "COURSE_TOP_RATED_SUCCESS";
export const COURSE_TOP_RATED_FAIL = "COURSE_TOP_RATED_FAIL";
export const COURSE_TOP_RATED_RESET = "COURSE_TOP_RATED_RESET";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";