export const LESSON_LIST_BY_COURSE_ID_REQUEST = "LESSON_LIST_BY_COURSE_ID_REQUEST";
export const LESSON_LIST_BY_COURSE_ID_SUCCESS = "LESSON_LIST_BY_COURSE_ID_SUCCESS";
export const LESSON_LIST_BY_COURSE_ID_FAIL = "LESSON_LIST_BY_COURSE_ID_FAIL";
export const LESSON_LIST_BY_COURSE_ID_RESET = "LESSON_LIST_BY_COURSE_ID_RESET";

export const LESSON_LIST_BY_ID_REQUEST = "LESSON_LIST_BY_ID_REQUEST";
export const LESSON_LIST_BY_ID_SUCCESS = "LESSON_LIST_BY_ID_SUCCESS";
export const LESSON_LIST_BY_ID_FAIL = "LESSON_LIST_BY_ID_FAIL";
export const LESSON_LIST_BY_ID_RESET = "LESSON_LIST_BY_ID_RESET";