export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

export const USER_GET_FAVORITE_REQUEST = "USER_GET_FAVORITE_REQUEST";
export const USER_GET_FAVORITE_SUCCESS = "USER_GET_FAVORITE_SUCCESS";
export const USER_GET_FAVORITE_FAIL = "USER_GET_FAVORITE_FAIL";
export const USER_GET_FAVORITE_RESET = "USER_GET_FAVORITE_RESET";

export const DELETE_FAVORITE_REQUEST = "DELETE_FAVORITE_REQUEST";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_FAIL = "DELETE_FAVORITE_FAIL";
export const DELETE_FAVORITE_RESET = "DELETE_FAVORITE_RESET";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
export const GET_ALL_USER_RESET = "GET_ALL_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const LIKED_COURSE_REQUEST = "LIKED_COURSE_REQUEST";
export const LIKED_COURSE_SUCCESS = "LIKED_COURSE_SUCCESS";
export const LIKED_COURSE_FAIL = "LIKED_COURSE_FAIL";
export const LIKED_COURSE_RESET = "LIKED_COURSE_RESET";